// MARK: - Full Header Generation

let bclGenericNames: Set<String> = [
    "List", "IList", "ICollection", "IEnumerable", "IReadOnlyList", "IReadOnlyCollection",
    "Dictionary", "IDictionary", "IReadOnlyDictionary", "SortedDictionary",
    "HashSet", "ISet", "KeyValuePair", "Nullable",
    "Action", "Func", "Tuple", "ValueTuple", "Task", "ValueTask",
    "IEquatable", "IComparable", "IFormattable", "IConvertible",
    "IDisposable", "ICloneable", "ISerializable",
    "EventHandler", "Predicate", "Comparison",
]

// MARK: - BFS collection of types + dependencies

/// Collect types via BFS, resolving referenced types. Returns (ordered parts, unresolved names).
@MainActor
private func collectTypesBFS(
    seeds: [(TypeInfo, String)],
    service: DecompilerService
) -> (parts: [(String, TypeInfo)], unresolved: [String]) {
    var parts: [(String, TypeInfo)] = []
    var visited: Set<String> = []
    var queue: [(TypeInfo, String)] = seeds
    var allReferenced: Set<String> = []
    var resolvedNames: Set<String> = []

    for (type_, _) in seeds {
        visited.insert(type_.fullName)
        resolvedNames.insert(cppIdentifier(type_.name))
    }

    while !queue.isEmpty {
        let (type_, typeAssemblyId) = queue.removeFirst()
        parts.append((generateFieldsOnlyType(type_), type_))
        resolvedNames.insert(cppIdentifier(type_.name))

        var referencedNames: [String] = []
        let fields = type_.members.filter { $0.kind == .field }
        let regularFields = fields.filter { backingFieldPropertyName($0.name) == nil }
        for f in regularFields {
            referencedNames.append(contentsOf: extractReferencedTypeNames(f.fieldType))
        }
        if let base = type_.baseType {
            referencedNames.append(contentsOf: extractReferencedTypeNames(base))
        }
        for iface in type_.interfaces {
            referencedNames.append(contentsOf: extractReferencedTypeNames(iface))
        }

        for name in referencedNames {
            allReferenced.insert(name)
            if bclGenericNames.contains(name) { continue }
            if let found = service.findTypeByShortName(name, preferredAssemblyId: typeAssemblyId) {
                if let typeInfo = service.getTypeDetails(assemblyId: found.assemblyId, token: found.token) {
                    if isBCLType(typeInfo.fullName) { continue }
                    if !visited.contains(typeInfo.fullName) {
                        visited.insert(typeInfo.fullName)
                        queue.append((typeInfo, found.assemblyId))
                    }
                }
            }
        }
    }

    // Find names that were referenced but never resolved to a real type
    let builtinCppNames: Set<String> = [
        "void", "bool", "char16_t", "int8_t", "uint8_t", "int16_t", "uint16_t",
        "int32_t", "uint32_t", "int64_t", "uint64_t", "float", "double",
        "intptr_t", "uintptr_t", "void*", "std",
    ]
    var unresolved: [String] = []
    for name in allReferenced.sorted() {
        let cppName = cppIdentifier(name)
        if resolvedNames.contains(cppName) { continue }
        if bclGenericNames.contains(name) { continue }
        if bclSkipNames.contains(name) { continue }
        if isBuiltinType(name) { continue }
        if builtinCppNames.contains(cppName) { continue }
        if isBCLType(name) { continue }
        unresolved.append(cppName)
    }

    return (parts, unresolved)
}

// MARK: - Standard includes block

private let standardIncludes = """
#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <functional>
#include <unordered_map>
#include <unordered_set>
#include <tuple>
#include <utility>
"""

// MARK: - Single-type header export (unchanged behavior)

@MainActor
func generateHeaderExport(rootType: TypeInfo, assemblyId: String, service: DecompilerService) -> String {
    let result = collectTypesBFS(seeds: [(rootType, assemblyId)], service: service)

    let guardName = cppIdentifier(rootType.name).uppercased() + "_H"
    var header = "// Generated by Ferrite\n\n"
    header += "#ifndef \(guardName)\n#define \(guardName)\n\n"
    header += standardIncludes + "\n"

    // Forward declarations for unresolved types
    if !result.unresolved.isEmpty {
        header += "\n// Forward declarations\n"
        for name in result.unresolved {
            header += "struct \(name);\n"
        }
        header += "\n"
    }

    // Dependencies first (reverse BFS order), root type last
    header += result.parts.reversed().map(\.0).joined(separator: "\n\n")
    header += "\n\n#endif // \(guardName)\n"
    return header
}

